# Default configuration for extension with alias: "antispam"
antispam:

    # Global default for whether included components should cause hard failures
    passive:              false

    # Global default for whether included components issue verbose or stealthy error messages
    stealth:              false

    # Allows you to globally disable all bundle functions, specifically for functional testing
    enabled:              true

    # Quarantine settings determine what to do with caught spam
    quarantine:

        # When false ham submits are also put in the quarantine, allowing you to analyze false negatives
        only_spam:            true
        file:
            dir:                  '%kernel.project_dir%/var/quarantine'
            max_days:             14

    # A named list of different profiles used throughout your application
    profiles:

        # Prototype: Name the profile
        name:

            # Defines whether measures in this profile issue stealthy error messages
            stealth:              true

            # Passive mode will not make any of the included checks actually fail validation, they will still be logged. Null inherits global setting
            passive:              null

            # Defines whether to disallow content resembling markup languages like HTML and BBCode
            banned_markup:
                html:                 true
                bbcode:               true

            # Simple array of phrases which are rejected when encountered in a submitted text field
            banned_phrases:
                phrases:              []

            # Banned script types, like Cyrillic or Arabic (see docs for commonly used ISO 15924 names)
            banned_scripts:
                scripts:              []
                max_characters:       null
                max_percentage:       0

            # Inject an invisible honeypot field in forms, baiting spambots to fill it in
            honeypot:

                # Base name of the injected field
                field:                ~ # Required
                attributes:

                    # Prototype
                    name:                 ~

            # Verify that time between retrieval and submission of a form is within human boundaries
            timer:

                # Base name of the injected field
                field:                _validation
                min:                  3
                max:                  3600

            # Configure limits to number of URLs permitted in text fields
            url_count:

                # Maximum number of URLs accepted per text field
                max:                  null

                # Maximum number of identical URLs accepted per text field
                max_identical:        null

